Object {
    "restaurant": Object {
      "R": Object {
        "has_menu_status": Object {
          "delivery": -1,
          "takeaway": -1,
        },
        "is_grocery_store": false,
        "res_id": 60426,
      },
      "all_reviews": Object {
        "reviews": Array [
          Object {
            "review": Array [],
          },
          Object {
            "review": Array [],
          },
          Object {
            "review": Array [],
          },
          Object {
            "review": Array [],
          },
          Object {
            "review": Array [],
          },
        ],
      },
      "all_reviews_count": 13,
      "apikey": "3c1c5402a58ee41964087ba5f486cccf",
      "average_cost_for_two": 200,
      "book_again_url": "",
      "book_form_web_view_url": "",
      "cuisines": "Biryani, Chinese",
      "currency": "Rs.",
      "deeplink": "zomato://restaurant/60426",
      "establishment": Array [
        "Quick Bites",
      ],
      "establishment_types": Array [],
      "events_url": "https://www.zomato.com/bangalore/shahi-chicken-biriyani-rajajinagar-bangalore/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
      "featured_image": "https://b.zmtcdn.com/data/pictures/6/60426/dc8635774c82fff19df05ac57e07f21f.jpg?output-format=webp",
      "has_online_delivery": 1,
      "has_table_booking": 0,
      "highlights": Array [
        "Dinner",
        "Delivery",
        "Lunch",
        "Cash",
        "Takeaway Available",
        "Indoor Seating",
      ],
      "id": "60426",
      "include_bogo_offers": true,
      "is_book_form_web_view": 0,
      "is_delivering_now": 0,
      "is_table_reservation_supported": 0,
      "is_zomato_book_res": 0,
      "location": Object {
        "address": "203, Dr. Rajkumar Road, Prakash Nagar, Opposite IDBI Bank, Rajajinagar, Bangalore",
        "city": "Bangalore",
        "city_id": 4,
        "country_id": 1,
        "latitude": "12.9933815461",
        "locality": "Rajajinagar",
        "locality_verbose": "Rajajinagar, Bangalore",
        "longitude": "77.5560404733",
        "zipcode": "",
      },
      "menu_url": "https://www.zomato.com/bangalore/shahi-chicken-biriyani-rajajinagar-bangalore/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
      "mezzo_provider": "OTHER",
      "name": "Shahi Chicken Biriyani",
      "offers": Array [],
      "opentable_support": 0,
      "phone_numbers": "+91 8088561652",
      "photo_count": 3,
      "photos_url": "https://www.zomato.com/bangalore/shahi-chicken-biriyani-rajajinagar-bangalore/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
      "price_range": 1,
      "store_type": "",
      "switch_to_order_menu": 0,
      "thumb": "https://b.zmtcdn.com/data/pictures/6/60426/dc8635774c82fff19df05ac57e07f21f.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
      "timings": "11:30 AM to 11 PM",
      "url": "https://www.zomato.com/bangalore/shahi-chicken-biriyani-rajajinagar-bangalore?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
      "user_rating": Object {
        "aggregate_rating": "3.9",
        "rating_color": "9ACD32",
        "rating_obj": Object {
          "bg_color": Object {
            "tint": "600",
            "type": "lime",
          },
          "title": Object {
            "text": "3.9",
          },
        },
        "rating_text": "Good",
        "votes": 1295,
      },
    },
  }